baseURL         = "https://pandaqi.com/"
theme           = "pandaqi"
title       	= "Pandaqi Games"
languageCode    = "en-US"
summaryLength 	= 18
SectionPagesMenu = "main"

[pagination]
  pagerSize = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = false

[permalinks]
  post = "/:slug/"

[build]
  noJSConfigInAssets = true

[params]
  enableBoardJS = false
  enableGameJS = false
  enableRulesJS = true

  simpleBanners = false
  heroImage = true

  title       = "Pandaqi"
  subtitle    = "Indie Game Developer"

  favicon     = "theme/favicon.png"

  description = "The official website of game studio Pandaqi"
  metaDescription = "The official website of game studio Pandaqi"
  
  pageNotFoundTitle = "404 - Page not found"

  num_masks   = 8
  all_colors  = ["red", "blue", "green", "yellow", "orange", "turquoise", "beige", "purple", "pink", "darkblue", "brown", "white", "black"]
  slogans     = ["No, the game will not have online multiplayer", "Creating local multiplayer games until someone tells me to stop", "Creator of friendships, destroyer of friendships", "Couch co-op for everyone (who has a couch)", "Helping gamers and non-gamers connect", "Different games for a different experience"]

[taxonomies]
  categories = 'categories'
  tags = 'tags'
  platform = 'platform'
  genres = 'genres'
  themes = 'themes'
  language = 'language'
  playtime = 'playtime'
  playercount = 'playercount'
  multiplayertype = 'multiplayertype'
  multiplayermode = 'multiplayermode'
  input = 'input'
  difficulty = 'difficulty'
  ages = 'ages'
  price = 'price'







